name: Activity Box

on:
  schedule:
    - cron: '*/1 * * * *'
  repository_dispatch:
    types: [build-event]
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: Avery2/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: Avery2
          GIST_ID: a8c0405f5734b8a323ddff8863b182c2
